[package]
name = "synacor-challenge"
version = "0.1.0"
edition = "2024"
default-run = "synacor-challenge"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
